---

- name: Verify uWSGI version already installed
  command: "{{ uwsgi_source }} --version"
  ignore_errors: yes
  register: versions
  changed_when: "versions.rc != 0 or versions.stdout != uwsgi_version"

- name: Install uWSGI
  action:
    module: pip
    name: uwsgi
    version: "{{ uwsgi_version }}"
    executable: "{{ uwsgi_executable | default(omit) }}"
    virtualenv_python: "{{ uwsgi_virtualenv_python | default(omit) }}"
    virtualenv: "{{ uwsgi_virtualenv | default(omit) }}"
  when: versions.changed
  notify: "start uWSGI service"