---

- name: "restart uWSGI service"
  action:
    module: service
    name: "{{ uwsgi_service_name }}"
    state: restarted

- name: "start uWSGI service"
  action:
    module: service
    name: "{{ uwsgi_service_name }}"
    state: started
